### PR TITLE
compile with -safe-string

### PR DESCRIPTION
**Pull request by cfcs**
depends on https://github.com/mirage/ocaml-xenstore/pull/35

### CODE REVIEW

**Comment by lindig** [comment]
As you might have seen, the Travis job failed with a type error. Do you have any comments how to fix this?

**Comment by gaborigloi** [comment]
I think that means mirage/ocaml-xenstore#35 has to be merged and `ocaml-xenstore` released before we can merge this.

**Comment by cfcs** [comment]
@lindig I'm sorry, I should have given more details.
As @gaborigloi inferred, the Travis CI test for this PR currently fails because `ocaml-xenstore` exposes functions with immutable `string` in the interface where they really are mutable `bytes`, and where this library (`ocaml-xenstore-clients`) uses them as such.
Once the PR at https://github.com/mirage/ocaml-xenstore/pull/35 gets merged, this PR should be good to go, too (I have only tested the code locally on `4.04`, but I think it should be fine).

**Comment by mseri** [comment]
I am merging this, but it will need `ocaml-xenstore` to be released before this could be released as well

**Comment by djs55** [comment]
FYI https://github.com/ocaml/opam-repository/pull/10941

**Comment by mseri** [comment]
Thanks!

**Pull request merged**
