### PR TITLE
Add some xenstore behavioural tests

### PR DESCRIPTION
**Pull request by jjd27**
Add some tests that can be run in dom0 to verify the correctness of xenstored.

These tests were based on server_test from https://github.com/xapi-project/ocaml-xenstore but have been adapted to talk to xenstored using the Unix domain socket in dom0.

### CODE REVIEW

**Comment by simonjbeaumont** [comment]
Shall we just ditched the dead code rather than leave it commented out? It will still be there in the git history cos you imported it all in 6b6eaa6.

**Comment by simonjbeaumont** [comment]
Also, we only need one "Regenerate OASIS" in this series at the end surely?

**Comment by jonludlam** [comment]
yeah, I think it needs some rebasing :-)

**Comment by jjd27** [comment]
> Shall we just ditched the dead code rather than leave it commented out? It will still be there in the git history cos you imported it all in 6b6eaa6.

I felt that it might be better to keep them visible so that someone in future who makes those tests possible doesn't need to remember that they had been implemented in the past.

> Also, we only need one "Regenerate OASIS" in this series at the end surely?

Each of them follows a separate change to the _oasis configuration file. Personally I prefer having it immediately following each change to improve bisectability.

**Comment by jonludlam** [comment]
I think I'd prefer to ditch the autogenerated code entirely and have a build-time dependency on oasis instead.

**Comment by jjd27** [comment]
I'd much prefer that too, but I was merely following suit with what has been done in the past.

**Comment by jonludlam** [comment]
OK, let's do that separately. Any other objections to merging this then?

**Comment by thomassa** [comment]
I've added the "needs updating" label in light of the comment above saying that the pull-request needs some rebasing.

**Comment by jjd27** [comment]
No-one commented on my defence of having three "Regenerate OASIS" commits... Do you really want me to get rid of two of them and break bisectability? There are three logically separate changes to _oasis.

**Comment by simonjbeaumont** [comment]
I think we could remove them altogether by having the first commit remove all
this autogen stuff from the repo as we want to do with most repos. Perhaps that
burden shouldn't be put on you though. We could always take these commits and
do the right thing.

**Comment by jjd27** [comment]
That was also discussed above, concluding with "OK, let's do that separately."

**Comment by simonjbeaumont** [comment]
Merged by https://github.com/xapi-project/ocaml-xenstore-clients/commit/0caeb99ca2c770e26d41ab9728ae0c62ecc67ccc:

    Rebasing on an additional commit to remove all the OASIS auto-generated
    build file from the repo. This has removed some unnecessary commits to
    regenerate these files from the original patch series.

**Comment by simonjbeaumont** [comment]
Also needed a change to the spec file in xen-api-libs-specs since we've picked up build dependencies on oasis and OUnit. I've released a new version of this library in https://github.com/xapi-project/ocaml-xenstore-clients/commit/9fa92d16cda98ec5a5c2b76c73bef8a6bcdd0f9d and updated the spec file in https://github.com/xenserver/xen-api-libs-specs/pull/141

**Pull request closed without merging**
